services:
  # === Laravel API (Docker Web Service) ===
  - type: web
    name: counter-api
    runtime: docker
    rootDir: apps/api
    dockerfilePath: apps/api/Dockerfile
    healthCheckPath: /up
    autoDeployTrigger: commit
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false            # set in dashboard on first create
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: counter-db
          property: connectionString  # Render injects full postgres URL

  # === Vue Static Site ===
  - type: web
    name: counter-web
    runtime: static
    rootDir: apps/web
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://REPLACE_ME/api  # update after API URL is known

databases:
  - name: counter-db
    databaseName: counter_db
    postgresMajorVersion: "17"
    plan: free
